# Generated by Django 5.1.6 on 2025-06-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avitoaccountdailystats',
            name='expenses_details',
        ),
    ]
