# Generated by Django 5.1.6 on 2025-06-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_avitoaccountdailystats_expenses_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoAccountWeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='Начало недели')),
                ('week_end_date', models.DateField(verbose_name='Конец недели')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='Период')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Всего звонков')),
                ('answered_calls', models.IntegerField(default=0, verbose_name='Отвеченные звонки')),
                ('missed_calls', models.IntegerField(default=0, verbose_name='Пропущенные звонки')),
                ('total_chats', models.IntegerField(default=0, verbose_name='Всего чатов')),
                ('new_chats', models.IntegerField(default=0, verbose_name='Новые чаты')),
                ('phones_received', models.IntegerField(default=0, verbose_name='Показы телефона')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Всего отзывов')),
                ('weekly_reviews', models.IntegerField(default=0, verbose_name='Отзывы за неделю')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего объявлений')),
                ('xl_promotion_count', models.IntegerField(default=0, verbose_name='Объявления с XL продвижением')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('contacts', models.IntegerField(default=0, verbose_name='Контакты')),
                ('favorites', models.IntegerField(default=0, verbose_name='В избранном')),
                ('balance_real', models.FloatField(default=0, verbose_name='Реальный баланс')),
                ('balance_bonus', models.FloatField(default=0, verbose_name='Бонусы')),
                ('advance', models.FloatField(default=0, verbose_name='Аванс')),
                ('cpa_balance', models.FloatField(default=0, verbose_name='CPA баланс')),
                ('weekly_expense', models.FloatField(default=0, verbose_name='Расход за неделю')),
                ('expenses_details', models.TextField(blank=True, help_text='JSON с детализацией расходов', null=True, verbose_name='Детализация расходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='bot.avitoaccount', verbose_name='Аккаунт Авито')),
            ],
            options={
                'verbose_name': 'Еженедельная статистика аккаунта',
                'verbose_name_plural': 'Еженедельная статистика аккаунтов',
                'ordering': ['-week_start_date'],
                'unique_together': {('avito_account', 'week_start_date')},
            },
        ),
    ]
