# Generated by Django 5.1.6 on 2025-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_avitoaccountweeklystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoaccountdailystats',
            name='tools_subscription_count',
            field=models.IntegerField(default=0, verbose_name='Объявления с подпиской на инструменты'),
        ),
        migrations.AddField(
            model_name='avitoaccountweeklystats',
            name='tools_subscription_count',
            field=models.IntegerField(default=0, verbose_name='Объявления с подпиской на инструменты'),
        ),
        migrations.AlterField(
            model_name='avitoaccountdailystats',
            name='total_calls',
            field=models.IntegerField(default=0, verbose_name='Всего новых звонков'),
        ),
        migrations.AlterField(
            model_name='avitoaccountweeklystats',
            name='total_calls',
            field=models.IntegerField(default=0, verbose_name='Всего новых звонков'),
        ),
    ]
